Always enable load balancing
microsoft/DeepSpeed-MII pull request #205
Opened 2023-06-20 17:25 UTC by TosinSeg

Always enable load balancing

2023-06-26 18:15 UTC, mrwyattii requested changes
I think we should also remove the `enable_load_balancing` pytest fixture.

Additionally, we should ensure that MII will work correctly if a hostfile is not specified. In the tests, we generate the hostfile, but perhaps this sort of functionality should be embedded in MII so that users are not required to generate one (especially if they are using just a single replica)

2023-06-26 18:15 UTC, mrwyattii commented on mii/client.py
> +    """
Let's remove this commented code

2023-06-26 18:15 UTC, mrwyattii commented on mii/server.py
>                  "hostfile must be provided if enable_load_balancing == True")
This error message will not make sense now

2023-06-26 18:15 UTC, mrwyattii commented on tests/test_local_deployment.py
> +        'replica_num': num_gpu * 1 // tensor_parallel,
```suggestion
        'replica_num': num_gpu // tensor_parallel,
```

2023-06-26 21:34 UTC, tohtana commented on mii/deployment.py
>      lb_config = None
Remove this line. `lb_config` is always initialized later.

2023-06-26 21:36 UTC, tohtana commented on mii/server.py
> +        deployment = lb_config.replica_configs
Now we don't need `deployment`

2023-06-27 16:39 UTC, mrwyattii approved these changes

2023-06-27 20:10 UTC, mrwyattii approved these changes

2023-06-27 20:20 UTC, tohtana approved these changes

2023-06-27 20:24 UTC, merged